import type { Mode } from "./api";

export interface ModeMeta {
  label: string;
  flavor: string;
  timed: boolean;
  slug: string;
  family: "speed" | "reading" | "arcade" | "rhythm" | "memory" | "training" | "precision";
  difficulty: "starter" | "focused" | "hard" | "expert";
  objective: string;
  rule: string;
  scoring: string;
  recommended: {
    durationSec: 30 | 60 | 90 | 120;
    pack: "core" | "tech" | "top1k" | "top5k" | "top10k" | "verbs" | "nouns" | "code";
  };
}

export const MODE_META: Record<Mode, ModeMeta> = {
  time: {
    label: "Sprint",
    flavor: "Timed word run.",
    timed: true,
    slug: "sprint",
    family: "speed",
    difficulty: "starter",
    objective: "Pure pace with no hidden rule.",
    rule: "Type each word and submit with Space. Accuracy keeps the run clean.",
    scoring: "WPM, accuracy, and streak are the whole story.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  quote: {
    label: "Quote",
    flavor: "Finish one full line.",
    timed: false,
    slug: "quote",
    family: "reading",
    difficulty: "starter",
    objective: "Complete a short passage without timer pressure.",
    rule: "Read ahead and type the passage in order. The run ends when the quote is done.",
    scoring: "Completion time and accuracy favor calm reading.",
    recommended: { durationSec: 60, pack: "core" },
  },
  meteor: {
    label: "Elephant Run",
    flavor: "Guide the elephant through falling word blocks.",
    timed: true,
    slug: "elephant-run",
    family: "arcade",
    difficulty: "focused",
    objective: "Clear falling words before they reach the line.",
    rule: "Type matching prefixes to lock the best target. Space chips or clears the locked block.",
    scoring: "Short target clears build streak; misses cost lives.",
    recommended: { durationSec: 60, pack: "core" },
  },
  zen: {
    label: "Flow",
    flavor: "No timer, endless words.",
    timed: false,
    slug: "flow",
    family: "training",
    difficulty: "starter",
    objective: "Warm up without pressure.",
    rule: "No timer. Stop when your hands feel ready.",
    scoring: "Local stats track consistency, not a countdown.",
    recommended: { durationSec: 60, pack: "core" },
  },
  pulse: {
    label: "Pulse",
    flavor: "Beat-timed scoring lane.",
    timed: true,
    slug: "pulse",
    family: "rhythm",
    difficulty: "focused",
    objective: "Submit on beat for bonus points.",
    rule: "Type normally, then press Space close to the pulse target.",
    scoring: "Perfect and great beat windows add score; off-beat submits count as mistakes.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  relay: {
    label: "Relay",
    flavor: "Mistakes push you backward.",
    timed: true,
    slug: "relay",
    family: "precision",
    difficulty: "focused",
    objective: "Recover from errors quickly.",
    rule: "A wrong submit sends you back two words. Backspace can undo the last submit.",
    scoring: "Clean chains matter more than risky speed.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  cipher: {
    label: "Cipher",
    flavor: "Global shift decode mode.",
    timed: true,
    slug: "cipher",
    family: "reading",
    difficulty: "hard",
    objective: "Decode shifted letters under time pressure.",
    rule: "The prompt is shifted; type the original decoded word.",
    scoring: "Pattern recognition and accuracy beat raw speed.",
    recommended: { durationSec: 90, pack: "core" },
  },
  drift: {
    label: "Drift",
    flavor: "Words drift side-to-side while you type.",
    timed: true,
    slug: "drift",
    family: "reading",
    difficulty: "focused",
    objective: "Keep reading while targets move.",
    rule: "Words slide horizontally. Lock your eyes ahead and keep typing.",
    scoring: "Stable pace through motion earns the best score.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  reverse: {
    label: "Reverse",
    flavor: "Reading order flips right-to-left.",
    timed: true,
    slug: "reverse",
    family: "reading",
    difficulty: "hard",
    objective: "Break autopilot reading habits.",
    rule: "The lane is displayed right-to-left, but each word is typed normally.",
    scoring: "Accuracy under reversed scanning is the focus.",
    recommended: { durationSec: 60, pack: "core" },
  },
  echo: {
    label: "Echo",
    flavor: "Type the previous word from memory.",
    timed: true,
    slug: "echo",
    family: "memory",
    difficulty: "hard",
    objective: "Train short-term recall.",
    rule: "After a clean word, repeat it from memory before moving forward.",
    scoring: "Perfect clears keep the echo chain alive.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  rogue: {
    label: "Rogue",
    flavor: "Pick run perks every few clears.",
    timed: true,
    slug: "rogue",
    family: "arcade",
    difficulty: "hard",
    objective: "Draft perks and adapt the run.",
    rule: "Every 20 clean clears offers three perks. Use keys 1-3 to pick.",
    scoring: "Perks can add score, time, shields, or combo bonuses.",
    recommended: { durationSec: 90, pack: "core" },
  },
  duel: {
    label: "Rhythm Duel",
    flavor: "Beat-timed run vs rival pace.",
    timed: true,
    slug: "rhythm-duel",
    family: "rhythm",
    difficulty: "hard",
    objective: "Outpace a rival while staying on beat.",
    rule: "Beat timing still matters, but the rival bar keeps pressure visible.",
    scoring: "Beat bonuses and steady progress beat panic typing.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  code: {
    label: "Code",
    flavor: "Type syntax-heavy programming words.",
    timed: true,
    slug: "code",
    family: "precision",
    difficulty: "focused",
    objective: "Practice code tokens and symbols.",
    rule: "Prompt chunks come from real-looking TypeScript snippets.",
    scoring: "Symbol accuracy and token rhythm matter.",
    recommended: { durationSec: 60, pack: "code" },
  },
  coach: {
    label: "Coach",
    flavor: "Adaptive drills from your weak patterns.",
    timed: true,
    slug: "coach",
    family: "training",
    difficulty: "focused",
    objective: "Attack your recent weak letter patterns.",
    rule: "Words containing missed bigrams/trigrams are weighted into the stream.",
    scoring: "Improvement comes from fewer repeated misses.",
    recommended: { durationSec: 90, pack: "top5k" },
  },
  blackout: {
    label: "Blackout",
    flavor: "Typed letters fade; trust muscle memory.",
    timed: true,
    slug: "blackout",
    family: "memory",
    difficulty: "hard",
    objective: "Type without visual confirmation.",
    rule: "Current word characters are masked as you type.",
    scoring: "Confidence and low correction count matter.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  chain: {
    label: "Chain",
    flavor: "Combo multipliers on long clean streaks.",
    timed: true,
    slug: "chain",
    family: "speed",
    difficulty: "focused",
    objective: "Protect a growing combo.",
    rule: "Clean words raise the combo; mistakes reset it.",
    scoring: "Long streaks add increasing bonus value.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  gravity: {
    label: "Gravity Flip",
    flavor: "Flow direction flips with time pulses.",
    timed: true,
    slug: "gravity-flip",
    family: "reading",
    difficulty: "expert",
    objective: "Reacquire the lane after direction flips.",
    rule: "The prompt direction flips every few seconds.",
    scoring: "Fast resets after each flip preserve pace.",
    recommended: { durationSec: 60, pack: "core" },
  },
  coop: {
    label: "Co-op Relay",
    flavor: "Two pilots alternate each cleared word.",
    timed: true,
    slug: "co-op-relay",
    family: "training",
    difficulty: "focused",
    objective: "Practice handoff rhythm.",
    rule: "The active pilot alternates each clean clear. Misses keep the turn.",
    scoring: "Balanced handoffs and clean turns build streak.",
    recommended: { durationSec: 60, pack: "core" },
  },
  infection: {
    label: "Infection",
    flavor: "Mistakes infect nearby words until cleaned.",
    timed: true,
    slug: "infection",
    family: "arcade",
    difficulty: "hard",
    objective: "Contain infected words before they spread pressure.",
    rule: "Mistakes infect nearby future words. Clearing infected words removes pressure.",
    scoring: "Clean cleanup avoids extra penalties.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  stealth: {
    label: "Stealth",
    flavor: "Only first and last letters stay visible.",
    timed: true,
    slug: "stealth",
    family: "memory",
    difficulty: "hard",
    objective: "Recognize word shapes from sparse clues.",
    rule: "Future words show only first and last letters.",
    scoring: "Shape recognition and low error count matter.",
    recommended: { durationSec: 60, pack: "top1k" },
  },
  chart: {
    label: "Rhythm Chart",
    flavor: "Strict beatmap windows for each submit.",
    timed: true,
    slug: "rhythm-chart",
    family: "rhythm",
    difficulty: "expert",
    objective: "Hit tighter rhythm windows than Pulse.",
    rule: "Submit each word inside a smaller beat window.",
    scoring: "Strict timing gives high precision rewards, misses are costly.",
    recommended: { durationSec: 90, pack: "top1k" },
  },
};

export const MODE_DETAILS: Record<Mode, string> = {
  time: "A straight speed run. Clean rhythm and sustained focus matter more than gimmicks here.",
  quote: "One complete passage with no timer pressure. Useful for endurance and punctuation control.",
  meteor: "Guide the elephant through falling word blocks. Targets stay slower, shorter, and easier to recover from.",
  zen: "Endless practice with no clock. Good for warming up or drilling accuracy without pressure.",
  pulse: "Every submit is judged against the beat. Better timing means cleaner bonus scoring.",
  relay: "Mistakes kick you backward through the prompt. Strong for recovery discipline under pressure.",
  cipher: "All words are shifted by the same amount. Decode fast and keep your pattern recognition sharp.",
  drift: "Words slide while you read them. Tracks eye control and quick target reacquisition.",
  reverse: "The reading direction flips. Good for breaking autopilot and forcing deliberate reads.",
  echo: "Clear a word, then repeat the last one from memory. Strong for recall and sequencing.",
  rogue: "Perks change the run every few clears. Higher variance, more aggressive pacing.",
  duel: "A rhythm-forward race against rival pace. Keep the beat or lose ground.",
  code: "Programming-heavy words and snippets. Good for syntax accuracy and symbol handling.",
  coach: "Weights words toward patterns you miss. Best mode for targeted improvement.",
  blackout: "Letters fade under your hands. Forces trust in muscle memory.",
  chain: "Long clean streaks stack combo value. Rewards consistency.",
  gravity: "The lane flow flips on a timer. Strong for reset speed and attention shifting.",
  coop: "Alternating turns create a relay cadence. Good for handoff rhythm and recovery.",
  infection: "Mistakes spread pressure into nearby words. Clean up quickly or the lane gets messy.",
  stealth: "Middle letters vanish. Focus on shape, memory, and word skeletons.",
  chart: "The strictest rhythm mode. Smaller hit windows, stronger precision demand.",
};

export const GAME_MODES = Object.keys(MODE_META) as Mode[];

export function slugForMode(mode: Mode): string {
  return MODE_META[mode].slug;
}

export function modeFromSlug(slug: string): Mode | null {
  const normalized = slug.toLowerCase();
  return GAME_MODES.find((mode) => MODE_META[mode].slug === normalized || mode === normalized) ?? null;
}

export function pathForMode(mode: Mode): string {
  return `/games/${slugForMode(mode)}`;
}
